name: CI - Rails Tests
on: [push, pull_request]
jobs:
  test-ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.7' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    - name: Install JS dependencies
      run: yarn install
    - name: Webpacker compilation
      run: NODE_ENV=test bundle exec rails assets:precompile
    - name: Run Ruby tests
      run: bundle exec rake
